#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                   ----[RedLight-GreenLight]----                                   #
#                                     ----[By Loving11ish]----                                      #
#                                   ----[mc.crapticraft.com]----                                    #
#                           ----[Made in collaboration with BoboCraft]----                          #
#                                   ----[play.bobocraft.com]----                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                   ----[Plugin Config File]----                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#Do you want players inventories to be wiped on join?
#This can bypassed using permission node 'redlight.bypass.joinwipe'
Wipe-inventory-on-join: false

#Do you want RedLight-GreenLight to handle server join spawn location (World/Server join lobby)?
Handle-player-join-spawn-event: true

#Do you want to send a welcome title for players joining the server?
Send-welcome-title: true
#Welcome-player-to-server-title:
Welcome-player-title: "&a&lWelcome To RedLight-GreenLight!"
Welcome-player-subtitle: "&ePlease use /redlight join"

#Do you want to disable the plugin use in certain worlds?
#To not use this, comment out the world's listed below and add '[]' after 'Disabled-worlds:'
Disabled-worlds:
  - "world_nether"
  - "world_the_end"

#Do you want the player to be made invulnerable on join?
Join-player-invulnerable: true

#Do you want the player to be made invulnerable on game leave?
Leave-player-invulnerable: true

#World/server join lobby position
#Join-lobby-position:
lobby-x: -233.0
lobby-y: 52.2
lobby-z: 24.0
lobby-yaw: 0.0
lobby-pitch: -0.0

#List below commands that are blocked during gameplay.
#This can bypassed using permission node 'redlight.bypass.commands'
#Any changes made to this list require a server restart or reload to take effect!
Blocked-commands-in-game:
  - "/spawn"
  - "/home"
  - "/sethome"
  - "/back"
  - "/tp"
  - "/suicide"
  - "/gamemode"
  - "/gmc"
  - "/gmsp"
  - "/thru"
  - "/tpa"
  - "/tpask"
  - "/warp"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                       ----[ARENA SETUP]----                                       #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#How many players should be in the arena for the game to start?
Arena-start-size: 4

#Set the arena starting position for the players
#Arena-position:
Arena-Start-x: -220.5
Arena-Start-y: 50.2
Arena-Start-z: 161.5
Arena-Start-yaw: 0.0
Arena-Start-pitch: -6.0

#The following section sets the detection of the winning zone.
#Simply make the floor of the winning area out of the below block combination.
#EXAMPLE: Block under player -          COAL_BLOCK
#EXAMPLE: Block under (-Y) COAL_BLOCK - GOLD_BLOCK
Top-trigger-block: COAL_BLOCK
Bottom-trigger-block: GOLD_BLOCK

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Below sets how long of a delay there is before the RedLight movement detection checks for movement.#
#This can be changed from '1 - 19'.  ANYTHING OVER 19 WILL CAUSE ERRORS!                            #
#                    DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU'RE DOING!                          #
RedLight-delay-checking-time: 12                                                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#Do you want to run any commands when a player wins?
Run-win-commands: true
#Enter the list of commands to be run below. (All commands are executed by the console)
#Any changes made to this list require a server restart or reload to take effect!
Win-commands-list:
  - "xp add %player% 10 levels"
  - "effect give %player% minecraft:speed 10 1"

#Do you want to run any commands when a player loses?
Run-lose-commands: true
#Enter the list of commands to be run below. (All commands are executed by the console)
#Any changes made to this list require a server restart or reload to take effect!
Lose-commands-list:
  - "effect give %player% minecraft:poison 10 0"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                   ----[RedLight-GreenLight]----                                   #
#                                     ----[By Loving11ish]----                                      #
#                                   ----[mc.crapticraft.com]----                                    #
#                           ----[Made in collaboration with BoboCraft]----                          #
#                                   ----[play.bobocraft.com]----                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                  ----[Plugin Messages File]----                                   #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#Game messages
Joined-game: "&aYou have joined the game.\n&aNow prepare to move only when told!"
Command-send-error: "&cSorry, that command cannot be run during gameplay!"
Failed-join-arena: "&cYou are already part of a game.\n&cUse &e/redlight leave &cto return to main lobby."
Successful-leave-game: "&aYou left the game and were teleported back to the lobby!"
Player-not-in-game: "&cYou are not currently in a &4&lRedLight&r&c-&a&lGreenLight &r&cgame!"
Waiting-for-enough-players: "&eYou are now in the queue to play.&r\n&eNow waiting for enough players to begin the game.&r\n&eUse &b/redlight leave &eto leave the game."
Game-already-running: "&cSorry there is already a &4&lRedLight&r&c-&a&lGreenLight &r&cgame running!"

Round-end-title: "&eNo One Won The Game!"
Round-end-subtitle: "&a&lGG's All Round"

GreenLight-message: "&aGreen Light"
#Do you want the RedLight message to be sent as a title & in chat?
RedLight-title-enable: true
RedLight-message: "&cRed Light"

Game-start-title: "&a&lLet The Race Begin!"
Game-start-subtitle: "&bBeat everyone to the finish line!"

Game-win-title: "&6&lCongratulations!  You Made it!"
Game-win-subtitle: "&bLets wait and see who will join you"

Game-loose-title: "&c&lOOF You didn't stand still!"
Game-loose-subtitle: "&4Better luck next time!"

#Do you want the players to be shown a title when they leave the game?
Show-leave-game-title: false
Game-leave-title: "&a&lYou Left The Game!"
Game-leave-subtitle: "&eThank you for playing!"

#Incorrect-command-syntax-console:
Syntax-error-1: "&4Please provide an argument!"
Syntax-error-2: "&4redlight reload"
Syntax-error-3: "&4redlight help"

Plugin-reload-successful: "&aThe config file has been reloaded!"
Reload-command-no-permission: "&4You do not have the permission &eredlight.reload &4needed to run that command"
Disabled-world-message: "&4&lRedLight&r&c-&a&lGreenLight has been disabled in this world."

#Plugin-update-available:
Update-1: "&4*-------------------------------------------*"
Update-2: "&bRedLight-GreenLight &c- A new version is available!"
Update-3: "&4*-------------------------------------------*"

#Plugin-no-new-update:
No-update-1: "&a*-------------------------------------------*"
No-update-2: "&bRedLight-GreenLight &a- Plugin is up to date!"
No-update-3: "&a*-------------------------------------------*"
Update-check-failure: "&bRedLight-GreenLight &4- Unable to check for updates! - &c"

#Plugin-help-chat-menu
Help-1: "&e[--------------- &b[RedLight-GreenLight] &e----------------]"
Help-2: "&f/redlight join &7- &dThis command joins the game."
Help-3: "&f/redlight leave &7- &dThis command leaves the game."
Help-4: "&f/redlight help &7- &dThis command shows this help menu."
Help-5: "&f/redlight reload &7- &dThis command reloads the config."
Help-6: "&e[------------------- &bPermissions &e---------------------]"
Help-7: "&f                               redlight.*"
Help-8: "&f                               redlight.help"
Help-9: "&f                               redlight.reload"
Help-10: "&f                               redlight.bypass.joinwipe"
Help-11: "&f                               redlight.bypass.commands"
Help-12: "&f                               redlight.bypass.gamemode"
Help-13: "&e[---------------------------------------------------]"
Help-14: "&f                               Plugin Version: &a%version%"
Help-15: "&e[---------------------------------------------------]"

Help-command-no-permission: "&4You do not have the permission &eredlight.help &4needed to run that command"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#