#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                   ----[RedLight-GreenLight]----                                   #
#                                     ----[By Loving11ish]----                                      #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                   ----[Plugin Config File]----                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#RedLightGreenLight config for version: ${project.version}

#General settings
developer-debug-mode:
  #Do you want to see a lot of debug messages in console when most actions are performed?
  #OPTIONS: 'true'/'false', PLACEHOLDERS: none, DEFAULT:'false'
  enabled: false

#Do you want players inventories to be wiped on join?
#This can bypassed using permission node 'redlight.bypass.joinwipe'
wipe-inventory-on-join: false

#Do you want RedLight-GreenLight to handle server join spawn location (World/Server join lobby)?
handle-player-join-spawn-event: true

#Do you want to send a welcome title for players joining the server?
send-welcome-title: true
#Welcome-player-to-server-title:
welcome-player-title: "&a&lWelcome To RedLight-GreenLight!"
welcome-player-subtitle: "&ePlease use /redlight join"

#Do you want to disable the plugin use in certain worlds?
#To not use this, comment out the world's listed below and add '[]' after 'Disabled-worlds:'
disabled-worlds:
  - "world_nether"
  - "world_the_end"

#Do you want the player to be made invulnerable on join?
join-player-invulnerable: true

#Do you want the player to be made invulnerable on game leave?
leave-player-invulnerable: true

#Do you want to disable ALL hunger loss?
disable-global-hunger-drain: false

#Do you want to disable hunger loss ONLY for players in a RedLight-GreenLight game?
disable-in-game-hunger-drain: true

#World/server join lobby position
#Join-lobby-position:
lobby-position:
  world-name: "world"
  x: -233.0
  y: 52.2
  z: 24.0
  yaw: 0.0
  pitch: -0.0

#List below commands that are blocked during gameplay.
#This can bypassed using permission node 'redlight.bypass.commands'
#Any changes made to this list require a server restart or reload to take effect!
blocked-commands-in-game:
  - "/spawn"
  - "/home"
  - "/sethome"
  - "/back"
  - "/tp"
  - "/suicide"
  - "/gamemode"
  - "/gmc"
  - "/gmsp"
  - "/thru"
  - "/tpa"
  - "/tpask"
  - "/warp"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                       ----[ARENA SETUP]----                                       #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#How many players should be in the arena for the game to start?
arena-start-size: 4

#How long do you want the game starting countdown to be? (In seconds.)
game-starting-countdown-length: 10

#How long do you want the total length of the game? (In seconds. 300 = 5 mins)
total-game-length: 300

#Set the arena starting position for the players
#Arena-position:
arena-start:
  world-name: "world"
  x: -220.5
  y: 50.0
  z: 161.5
  yaw: 0.0
  pitch: -6.0

#Do you want the losers to spectate the game in progress?
losers-spectate-game: true
#Set the location of the spectator spawn.
#Spectator-position:
arena-spectate:
  world-name: "world"
  x: -220.5
  y: 50.0
  z: 161.5
  yaw: 0.0
  pitch: -6.0

#The following section sets the detection of the WINNING ZONE.
#Simply make the floor of the WINNING ZONE out of the below block combination.
#EXAMPLE: Block under player -          COAL_BLOCK
#EXAMPLE: Block under (-Y) COAL_BLOCK - GOLD_BLOCK
top-trigger-block: COAL_BLOCK
bottom-trigger-block: GOLD_BLOCK

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#Below sets how long of a delay there is before the RedLight movement detection checks for movement.#
#This can be changed from '50 - 950'.  ANYTHING OVER 950 WILL CAUSE ERRORS!                         #
#                    DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU'RE DOING!                          #
redLight-delay-checking-time: 600                                                                   #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#Do you want to run any commands when a player wins?
run-win-commands: true
#Enter the list of commands to be run below. (All commands are executed by the console)
#Any changes made to this list require a server restart or reload to take effect!
win-commands-list:
  - "xp add %player% 10 levels"
  - "effect give %player% minecraft:speed 10 1"

#Do you want to run any commands when a player loses?
run-lose-commands: true
#Enter the list of commands to be run below. (All commands are executed by the console)
#Any changes made to this list require a server restart or reload to take effect!
lose-commands-list:
  - "effect give %player% minecraft:poison 10 0"

#Do you want players to be struck with lightning whn they loose?
smite-losing-players: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
