name: RedLightGreenLight
version: '${project.version}'
main: me.loving11ish.redlightgreenlight.RedLightGreenLight
api-version: 1.13
folia-supported: true
load: POSTWORLD
authors: [ Loving11ish ]
description: A Red Light, Green Light mini-game based off the Netflix series Squid Games.

commands:
  redlight:
    description: The main command.
    usage: /redlight <command>
    aliases: [ rd, red, rlgl ]

permissions:
  redlight.*:
    description: Gives access to all RedLight-GreenLight features.
    default: op
    children:

      redlight.help:
        description: Allows the player to view the help menu.
        default: true
      redlight.reload:
        description: Allows the player to reload the plugin.
        default: op

      redlight.command.*:
        description: Allows the player to use all RedLight-GreenLight commands.
        default: op
        children:
          redlight.command.joinall:
            description: Allows the player to force join all players to the game.
            default: op
          redlight.command.leaveall:
            description: Allows the player to force leave all players from the game.
            default: op

      redlight.bypass.*:
        description: Allows the player to bypass all protections.
        default: op
        children:
          redlight.bypass.joinwipe:
            description: Allows the player to bypass the inventory wipe on join.
            default: op
          redlight.bypass.commands:
            description: Allows the player to bypass the blocked commands.
            default: op
          redlight.bypass.gamemode:
            description: Allows the player to bypass the gamemode change.
            default: op
